# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fp.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from tst.send_email import send_mail


class ForgotPass(QtWidgets.QDialog):

    def __init__(self):
        super(ForgotPass, self).__init__()

        self.setObjectName("ForgotPass")
        self.resize(436, 376)
        self.lbl_fp = QtWidgets.QLabel(self)
        self.lbl_fp.setGeometry(QtCore.QRect(30, 20, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_fp.setFont(font)
        self.lbl_fp.setObjectName("lbl_fp")
        self.lbl_username = QtWidgets.QLabel(self)
        self.lbl_username.setGeometry(QtCore.QRect(28, 70, 71, 16))
        self.lbl_username.setObjectName("lbl_username")
        self.line_username = QtWidgets.QLineEdit(self)
        self.line_username.setGeometry(QtCore.QRect(108, 70, 251, 21))
        self.line_username.setObjectName("line_username")
        self.lbl_email = QtWidgets.QLabel(self)
        self.lbl_email.setGeometry(QtCore.QRect(28, 110, 61, 16))
        self.lbl_email.setObjectName("lbl_email")
        self.line_email = QtWidgets.QLineEdit(self)
        self.line_email.setGeometry(QtCore.QRect(108, 110, 251, 21))
        self.line_email.setObjectName("line_email")

        self.btn_resetpass = QtWidgets.QPushButton(self)
        self.btn_resetpass.setGeometry(QtCore.QRect(230, 170, 131, 32))
        self.btn_resetpass.setObjectName("btn_resetpass")
        self.btn_resetpass.clicked.connect(self.resetpass_btn_handler)

        self.lbl_note_msg = QtWidgets.QLabel(self)
        self.lbl_note_msg.setEnabled(True)
        self.lbl_note_msg.setGeometry(QtCore.QRect(20, 240, 391, 61))
        self.lbl_note_msg.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_note_msg.setScaledContents(False)
        self.lbl_note_msg.setWordWrap(True)
        self.lbl_note_msg.setObjectName("lbl_note_msg")
        self.lbl_note = QtWidgets.QLabel(self)
        self.lbl_note.setGeometry(QtCore.QRect(20, 220, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_note.setFont(font)
        self.lbl_note.setScaledContents(False)
        self.lbl_note.setObjectName("lbl_note")

        QtCore.QMetaObject.connectSlotsByName(self)

        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("ForgotPass", "Forgot Password?"))
        self.lbl_fp.setText(_translate("ForgotPass", "Forgot Password?"))
        self.lbl_username.setText(_translate("ForgotPass", "Username"))
        self.lbl_email.setText(_translate("ForgotPass", "Email"))
        self.btn_resetpass.setText(_translate("ForgotPass", "Reset Password"))
        self.lbl_note_msg.setText(_translate("ForgotPass",
                                             "Password will be automatically reset and a new password will be sent to your email. Please use the password in your email to login and change your new password."))
        self.lbl_note.setText(_translate("ForgotPass", "Note:"))

    def forgotpass_getValues(self):
        username = self.line_username.text()
        email = self.line_email.text()
        return {"username": username, "email": email}

    def resetpass_btn_handler(self):
        fp_val_dict = self.forgotpass_getValues()
        email_id = fp_val_dict['email']
        send_mail(email_id)
        self.w2 = QtWidgets.QMessageBox()
        self.w2.setIcon(QtWidgets.QMessageBox.Information)
        pop_up_msg = 'Password Reset Email Sent!'
        self.w2.setText(pop_up_msg)
        self.w2.show()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = ForgotPass()
    ui.show()
    sys.exit(app.exec_())
