# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fp.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(436, 376)
        self.lbl_fp = QtWidgets.QLabel(Dialog)
        self.lbl_fp.setGeometry(QtCore.QRect(30, 20, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_fp.setFont(font)
        self.lbl_fp.setObjectName("lbl_fp")
        self.lbl_username = QtWidgets.QLabel(Dialog)
        self.lbl_username.setGeometry(QtCore.QRect(28, 70, 71, 16))
        self.lbl_username.setObjectName("lbl_username")
        self.line_username = QtWidgets.QLineEdit(Dialog)
        self.line_username.setGeometry(QtCore.QRect(108, 70, 251, 21))
        self.line_username.setObjectName("line_username")
        self.lbl_email = QtWidgets.QLabel(Dialog)
        self.lbl_email.setGeometry(QtCore.QRect(28, 110, 61, 16))
        self.lbl_email.setObjectName("lbl_email")
        self.line_email = QtWidgets.QLineEdit(Dialog)
        self.line_email.setGeometry(QtCore.QRect(108, 110, 251, 21))
        self.line_email.setObjectName("line_email")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(230, 170, 131, 32))
        self.pushButton.setObjectName("pushButton")
        self.lbl_note_msg = QtWidgets.QLabel(Dialog)
        self.lbl_note_msg.setEnabled(True)
        self.lbl_note_msg.setGeometry(QtCore.QRect(20, 240, 391, 61))
        self.lbl_note_msg.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_note_msg.setScaledContents(False)
        self.lbl_note_msg.setWordWrap(True)
        self.lbl_note_msg.setObjectName("lbl_note_msg")
        self.lbl_note = QtWidgets.QLabel(Dialog)
        self.lbl_note.setGeometry(QtCore.QRect(20, 220, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_note.setFont(font)
        self.lbl_note.setScaledContents(False)
        self.lbl_note.setObjectName("lbl_note")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Forgot Password?"))
        self.lbl_fp.setText(_translate("Dialog", "Forgot Password?"))
        self.lbl_username.setText(_translate("Dialog", "Username"))
        self.lbl_email.setText(_translate("Dialog", "Email"))
        self.pushButton.setText(_translate("Dialog", "Reset Password"))
        self.lbl_note_msg.setText(_translate("Dialog", "Password will be automatically reset and a new password will be sent to your email. Please use the password in your email to login and change your new password."))
        self.lbl_note.setText(_translate("Dialog", "Note:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
