# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from db import get_postgres_con
from gui.drafttest import Ui_MainWindow


class Login(QtWidgets.QDialog):
    def __init__(self):
        super(Login, self).__init__()

        self.setObjectName("Dialog")
        self.resize(445, 319)

        self.lbl_usrname = QtWidgets.QLabel('Login', self)
        self.lbl_usrname.setGeometry(QtCore.QRect(40, 80, 101, 16))
        self.lbl_usrname.setObjectName("lbl_usrname")

        self.lbl_pwd = QtWidgets.QLabel('Login', self)
        self.lbl_pwd.setGeometry(QtCore.QRect(40, 120, 61, 16))
        self.lbl_pwd.setObjectName("lbl_pwd")
        self.line_usrname = QtWidgets.QLineEdit(self)
        self.line_usrname.setGeometry(QtCore.QRect(150, 80, 231, 21))
        self.line_usrname.setObjectName("line_usrname")

        self.line_pwd = QtWidgets.QLineEdit(self)
        self.line_pwd.setGeometry(QtCore.QRect(150, 120, 231, 21))
        self.line_pwd.setObjectName("line_pwd")
        # Hide Password
        self.line_pwd.setEchoMode(QtWidgets.QLineEdit.Password)

        self.lbl_heading = QtWidgets.QLabel('Login', self)
        self.lbl_heading.setGeometry(QtCore.QRect(190, 30, 41, 16))
        self.lbl_heading.setObjectName("lbl_heading")

        self.btn_login = QtWidgets.QPushButton('Login', self)
        self.btn_login.setGeometry(QtCore.QRect(270, 170, 113, 32))
        self.btn_login.setObjectName("btn_login")
        self.btn_login.clicked.connect(self.login_btn_handler)

        self.btn_signup = QtWidgets.QPushButton('Login', self)
        self.btn_signup.setGeometry(QtCore.QRect(150, 170, 113, 32))
        self.btn_signup.setObjectName("btn_signup")
        self.btn_forgotpwd = QtWidgets.QPushButton('Login', self)
        self.btn_forgotpwd.setGeometry(QtCore.QRect(150, 210, 191, 32))
        self.btn_forgotpwd.setObjectName("btn_forgotpwd")

        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Login", "Connect"))
        self.lbl_usrname.setText(_translate("Login", "Username/Email"))
        self.lbl_pwd.setText(_translate("Login", "Password"))
        self.lbl_heading.setText(_translate("Login", "LOGIN"))
        self.btn_login.setText(_translate("Login", "Login"))
        self.btn_signup.setText(_translate("Login", "Signup?"))
        self.btn_forgotpwd.setText(_translate("Login", "Forgot Your Password?"))

        QtCore.QMetaObject.connectSlotsByName(self)
        # self.user_list = self.login_btn_handler()

    # def login_getValues(self):
    #     self.user_name = self.line_usrname.text()
    #     self.user_password = self.line_pwd.text()
    #     pass

    def login_btn_handler(self):

        self.w1 = QtWidgets.QMessageBox()

        user_name = self.line_usrname.text()
        user_pass = self.line_pwd.text()
        print(user_name + " " + user_pass)
        user_list = get_postgres_con.connect(username=user_name, password=user_pass)
        if len(user_list) == 1:
            self.accept()
            return user_list
        else:
            self.w1.setIcon(QtWidgets.QMessageBox.Warning)
            pop_up_msg = 'Login Credentials Incorrect!'
            self.w1.setText(pop_up_msg)
            self.w1.show()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    login = Login()
    if (login.exec_()) == QtWidgets.QDialog.Accepted:
        print("ACCEPTED")
        window = Ui_MainWindow()
        window.show()
        sys.exit(app.exec_())
    else:
        print("WE ARE IN ELSE")

# app = QtWidgets.QApplication(sys.argv)
# Dialog = QtWidgets.QDialog()
# ui = Login()
# ui.setupUi(Dialog)
# Dialog.show()
# if (app.exec_()) == Dialog.Accepted:
#     print("ACCEPTED")
# else:
#     print(Dialog.Accepted)
#     print("WE ARE IN ELSE")


# sys.exit(app.exec_())

# steganoapp = QtWidgets.QApplication(sys.argv)
# MainWindow = QtWidgets.QMainWindow()
# ui = Ui_MainWindow()
# ui.setupUi(MainWindow)
# MainWindow.show()
# sys.exit(steganoapp.exec_())

# MainWindow = QtWidgets.QMainWindow()
# ui = Ui_MainWindow()
# ui.setupUi(MainWindow)
# MainWindow.show()

# app = QtWidgets.QApplication(sys.argv)
# MainWindow = QtWidgets.QMainWindow()
# ui = Ui_MainWindow()
# ui.setupUi(MainWindow)
# MainWindow.show()
