# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from db import get_postgres_con
from gui.drafttest import Ui_MainWindow
from gui.signup import SignUp


class Login(QtWidgets.QDialog):
    def __init__(self):
        super(Login, self).__init__()

        self.setObjectName("Dialog")
        self.resize(445, 319)

        self.lbl_usrname = QtWidgets.QLabel('Login', self)
        self.lbl_usrname.setGeometry(QtCore.QRect(40, 80, 101, 16))
        self.lbl_usrname.setObjectName("lbl_usrname")

        self.lbl_pwd = QtWidgets.QLabel('Login', self)
        self.lbl_pwd.setGeometry(QtCore.QRect(40, 120, 61, 16))
        self.lbl_pwd.setObjectName("lbl_pwd")
        self.line_usrname = QtWidgets.QLineEdit(self)
        self.line_usrname.setGeometry(QtCore.QRect(150, 80, 231, 21))
        self.line_usrname.setObjectName("line_usrname")

        self.line_pwd = QtWidgets.QLineEdit(self)
        self.line_pwd.setGeometry(QtCore.QRect(150, 120, 231, 21))
        self.line_pwd.setObjectName("line_pwd")
        # Hide Password
        self.line_pwd.setEchoMode(QtWidgets.QLineEdit.Password)

        self.lbl_heading = QtWidgets.QLabel('Login', self)
        self.lbl_heading.setGeometry(QtCore.QRect(190, 30, 41, 16))
        self.lbl_heading.setObjectName("lbl_heading")

        self.btn_login = QtWidgets.QPushButton('Login', self)
        self.btn_login.setGeometry(QtCore.QRect(270, 170, 113, 32))
        self.btn_login.setObjectName("btn_login")
        self.btn_login.clicked.connect(self.login_btn_handler)

        self.btn_signup = QtWidgets.QPushButton('Login', self)
        self.btn_signup.setGeometry(QtCore.QRect(150, 170, 113, 32))
        self.btn_signup.setObjectName("btn_signup")
        self.btn_signup.clicked.connect(self.login_signup_btn_handler)

        self.btn_forgotpwd = QtWidgets.QPushButton('Login', self)
        self.btn_forgotpwd.setGeometry(QtCore.QRect(150, 210, 191, 32))
        self.btn_forgotpwd.setObjectName("btn_forgotpwd")

        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Login", "Connect"))
        self.lbl_usrname.setText(_translate("Login", "Username/Email"))
        self.lbl_pwd.setText(_translate("Login", "Password"))
        self.lbl_heading.setText(_translate("Login", "LOGIN"))
        self.btn_login.setText(_translate("Login", "Login"))
        self.btn_signup.setText(_translate("Login", "Signup?"))
        self.btn_forgotpwd.setText(_translate("Login", "Forgot Your Password?"))

        QtCore.QMetaObject.connectSlotsByName(self)
        # self.user_list = self.login_btn_handler()

        # self.signup_dialog = SignUp()

    def login_getValues(self):
        user_name = self.line_usrname.text()
        user_password = self.line_pwd.text()
        return {"username": user_name, "userpass": user_password}

    def login_btn_handler(self):
        self.w1 = QtWidgets.QMessageBox()
        login_val_dict = self.login_getValues()
        username = login_val_dict["username"]
        userpass = login_val_dict["userpass"]
        print(username + "  " + userpass)
        user_list = get_postgres_con.connect(username=username, password=userpass)
        if len(user_list) == 1:
            self.accept()
            return user_list
        else:
            self.w1.setIcon(QtWidgets.QMessageBox.Warning)
            pop_up_msg = 'Login Credentials Incorrect!'
            self.w1.setText(pop_up_msg)
            self.w1.show()

    def login_signup_btn_handler(self):
        print("CLICKED SIGNUP")
        signup_dialog = SignUp()
        signup_dialog.exec()
        signup_dialog.show()
        signup_dialog.close()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    login = Login()
    if (login.exec_()) == QtWidgets.QDialog.Accepted:
        print("ACCEPTED", login.login_getValues())
        window = Ui_MainWindow(username=login.login_getValues()["username"])
        window.show()
        sys.exit(app.exec_())
    else:
        print("WE ARE IN ELSE")
