# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from db.get_postgres_con import insert_signup


class SignUp(QtWidgets.QDialog):

    def __init__(self):
        super(SignUp, self).__init__()

        self.setObjectName("SignUp")
        self.resize(373, 527)
        self.lbl_signup = QtWidgets.QLabel(self)
        self.lbl_signup.setGeometry(QtCore.QRect(40, 20, 91, 41))
        self.lbl_signup.setStyleSheet("font: 24pt \".AppleSystemUIFont\";")
        self.lbl_signup.setObjectName("lbl_signup")
        self.lbl_firstname = QtWidgets.QLabel(self)
        self.lbl_firstname.setGeometry(QtCore.QRect(40, 90, 71, 16))
        self.lbl_firstname.setObjectName("lbl_firstname")
        self.line_firstname = QtWidgets.QLineEdit(self)
        self.line_firstname.setGeometry(QtCore.QRect(40, 120, 131, 21))
        self.line_firstname.setObjectName("line_firstname")
        self.lbl_emailadd = QtWidgets.QLabel(self)
        self.lbl_emailadd.setGeometry(QtCore.QRect(40, 160, 91, 16))
        self.lbl_emailadd.setObjectName("lbl_emailadd")
        self.line_emailadd = QtWidgets.QLineEdit(self)
        self.line_emailadd.setGeometry(QtCore.QRect(40, 190, 281, 21))
        self.line_emailadd.setObjectName("line_emailadd")
        self.lbl_password = QtWidgets.QLabel(self)
        self.lbl_password.setGeometry(QtCore.QRect(40, 300, 71, 16))
        self.lbl_password.setObjectName("lbl_password")

        self.line_password = QtWidgets.QLineEdit(self)
        self.line_password.setGeometry(QtCore.QRect(40, 330, 281, 21))
        self.line_password.setObjectName("line_password")
        self.line_password.setEchoMode(QtWidgets.QLineEdit.Password)

        self.line_lastname = QtWidgets.QLineEdit(self)
        self.line_lastname.setGeometry(QtCore.QRect(190, 120, 131, 21))
        self.line_lastname.setObjectName("line_lastname")

        self.lbl_lastname = QtWidgets.QLabel(self)
        self.lbl_lastname.setGeometry(QtCore.QRect(190, 90, 71, 16))
        self.lbl_lastname.setObjectName("lbl_lastname")

        self.line_confirmpassword = QtWidgets.QLineEdit(self)
        self.line_confirmpassword.setGeometry(QtCore.QRect(40, 400, 281, 21))
        self.line_confirmpassword.setObjectName("line_confirmpassword")
        self.line_confirmpassword.setEchoMode(QtWidgets.QLineEdit.Password)

        self.lbl_confirmpassword = QtWidgets.QLabel(self)
        self.lbl_confirmpassword.setGeometry(QtCore.QRect(40, 370, 111, 16))
        self.lbl_confirmpassword.setObjectName("lbl_confirmpassword")
        self.line_setusername = QtWidgets.QLineEdit(self)
        self.line_setusername.setGeometry(QtCore.QRect(40, 260, 281, 21))
        self.line_setusername.setObjectName("line_setusername")
        self.lbl_setusername = QtWidgets.QLabel(self)
        self.lbl_setusername.setGeometry(QtCore.QRect(40, 230, 121, 16))
        self.lbl_setusername.setObjectName("lbl_setusername")
        self.btn_signup = QtWidgets.QPushButton(self)
        self.btn_signup.setGeometry(QtCore.QRect(40, 450, 113, 32))
        self.btn_signup.setObjectName("btn_signup")
        self.btn_signup.clicked.connect(self.signup_btn_handler)

        QtCore.QMetaObject.connectSlotsByName(self)

        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("SignUp", "Dialog"))
        self.lbl_signup.setText(_translate("SignUp", "Sign Up"))
        self.lbl_firstname.setText(_translate("SignUp", "First Name"))
        self.lbl_emailadd.setText(_translate("SignUp", "Email Address"))
        self.lbl_password.setText(_translate("SignUp", "Password"))
        self.lbl_lastname.setText(_translate("SignUp", "Last Name"))
        self.lbl_confirmpassword.setText(_translate("SignUp", "Confirm Password"))
        self.lbl_setusername.setText(_translate("SignUp", "Set username"))
        self.btn_signup.setText(_translate("SignUp", "Sign Up"))

    def signup_getValues(self):
        firstname = self.line_firstname.text()
        lastname = self.line_lastname.text()
        emailadd = self.line_emailadd.text()
        set_username = self.line_setusername.text()
        password = self.line_password.text()
        confirmpassword = self.line_confirmpassword.text()
        return {"firstname": firstname, "lastname": lastname,
                "emailadd": emailadd, "set_username": set_username,
                "password": password, "confirmpassword": confirmpassword}

    def signup_btn_handler(self):
        self.w2 = QtWidgets.QMessageBox()
        print(self.signup_getValues())

        signup_val_dict = self.signup_getValues()
        fname = signup_val_dict["firstname"]
        lname = signup_val_dict["lastname"]
        email = signup_val_dict["emailadd"]
        user_name = signup_val_dict["set_username"]
        user_pass = signup_val_dict["password"]
        confirm_user_pass = signup_val_dict["confirmpassword"]

        if user_pass != confirm_user_pass:
            self.w2.setIcon(QtWidgets.QMessageBox.Warning)
            pop_up_msg = 'Passwords do not match!'
            self.w2.setText(pop_up_msg)
            self.w2.show()
        elif fname == "" or lname == "" or email == "" or user_name == "" or user_pass == "" or confirm_user_pass == "":
            self.w2.setIcon(QtWidgets.QMessageBox.Warning)
            pop_up_msg = 'Please enter all fields!'
            self.w2.setText(pop_up_msg)
            self.w2.show()
        else:
            insert_signup(fname, lname, email, user_name, user_pass)
            self.w2.setIcon(QtWidgets.QMessageBox.Information)
            pop_up_msg = 'SignUp Successful!'
            self.w2.setText(pop_up_msg)
            self.w2.show()

        # check and insert signup values to database and show pop up
        # self.close()

# if __name__ == "__main__":
#     import sys
#
#     app = QtWidgets.QApplication(sys.argv)
#     ui = SignUp()
#     ui.show()
#     sys.exit(app.exec_())
